### PR TITLE
bash script to combine two NTFS file systems volume images into a single partitioned image

### PR DESCRIPTION
**Pull request by Sim4n6**
Hi, 

this repository is very interesting and while working on Slack_handler I had to combine two ntfs speciments/partitions into a single disk image with a partition table. I made this little script that produces the result of combination into original.raw

I can improve it more to take for instance more specimens in input. Please feel free to suggest :+1:

### CODE REVIEW

**Comment by joachimmetz** [comment]
@Sim4n6 thx for the PR. The goal/scope of this project is mainly to produce reproducible NTFS test data. Could you provide me with a bit of more context of how this script would contribute to that goal. Wouldn't be more straight forward to just create test data with multiple partitions to start with?

**Comment by Sim4n6** [comment]
Well, take the following example: an examiner produced the NTFS specimens and NTFS behavior specimens. The results could not be checked by any tool that digest disk images.

Yes, it is more straight forward to create test data with multiple partitions from the beginning. But the little script is a separate one. I did not want to modify the other two until I get your feedback.

If you judge that this little script is outside of the scope of the repo feel free to close the PR. I am just giving back :)

**Comment by joachimmetz** [comment]
> The results could not be checked by any tool that digest disk images.

Do I assume correctly that with this you mean a tool that expects the image to start with a MBR and/or GPT partitions table (or equiv)?

> If you judge that this little script is outside of the scope of the repo feel free to close the PR. I am just giving back :)

Don't get me wrong your contributions are much appreciated. Note that I'm assessing these also from a long-term maintenance perspective.

**Comment by Sim4n6** [comment]
> Do I assume correctly that with this you mean a tool that expects the image to start with a MBR and/or GPT partitions table (or equiv)?

definitely 

> Don't get me wrong your contributions are much appreciated. Note that I'm assessing these also from a long-term maintenance perspective.

No problem.

**Comment by Sim4n6** [comment]
We could also be more straight forward by creating test_data (a disk image with a partition table containing a single partition) like I did [here](https://github.com/Sim4n6/Slack_handler/tree/master/Scripts). If you want I can PR it.

**Comment by joachimmetz** [comment]
thx for the suggestion but the script uses external files to create the test data? As I said before the goal of this project is to create reproducible NTFS test data (for context see https://en.wikipedia.org/wiki/Reproducibility). Reproducibility cannot be guaranteed when relying on external files that are not included. The idea is to keep the scripts simple, straightforward and covering known data format "edge" cases.

Can you explain a bit your use case for these scripts? For Slack_handler I can imagine that you want to produce test data that includes all types of NTFS slack space. It is not clear to me how adding a directory of files to a NTFS file system is going to provide you with that.

**Comment by Sim4n6** [comment]
Adding directory of files 📂 for my case is a scenario I need to test Slack-handler.

The external files come from Govdocs1 Dataset.

I think you are right. Both scripts fit for slack-handler test need but outside the scope of NTFS-specimens.

Thank you (I'm still learning you know :))

**Pull request closed without merging**
